### ISSUE TITLE
Plugin dumps if g:fileselector_exclude_pattern is not set

### ISSUE THREAD

**Issue by Sirius-A** [andrewferrier/vim-fileselector#12]
Hey thank you very much for this cool plugin. 

I get the following error after installing the plugin:

``` txt
Error detected while processing function <SNR>77_MRU_AddFile:
line    6:
E691: Can only compare List with List
E15: Invalid expression: g:fileselector_exclude_pattern !=# []
Press ENTER or type command to continue
```

If I set this in my vimrc everything works fine

``` vim
  let g:fileselector_exclude_pattern = ["/.git"]
```

NVIM v0.3.8

**Comment by Sirius-A** [comment]
I suspect that line 12 should be changed to

``` vim
    let g:fileselector_exclude_pattern=['/.git']
``` 
as it expects a list later on. I can submit a PR if you like, but I'm not sure if my gut is correct :sweat_smile:

**Comment by andrewferrier** [comment]
I think you are correct, and I never spotted it because I always set this explicitly! I’ll double check and go when I’m back to my machine. Thanks!

**Comment by andrewferrier** [comment]
Thanks - you were right! This should be fixed now.
